### ISSUE TITLE
Send notes to different MIDI channels

### ISSUE THREAD

**Issue by karlsander** [dvhdr/launchpad-pro#10]
I would like to send notes out to different midi channels concurrently. Is this already possible and i'm just missing how? If not, it would be a good addition.

**Comment by dvhdr** [comment]
No separate parameter for channel - you just need to put them into the status byte, eg:

unsigned char channel = 3;
status |= channel;

**Comment by karlsander** [comment]
Ah thanks. My knowledge of the midi protocoll is still kinda limited. No further feature is need then.
