### ISSUE TITLE
skip vagrant on OS X

### ISSUE THREAD

**Issue by faroit** [dvhdr/launchpad-pro#12]
I really like the vagrant workflow since it increases reproducibility and cross platform portability. But... it's kind of slow and needs some effort to setup.

I just found out that compiling on OS X is actually very easy if the ARM eabi toolchain is installed. To make this even easier, I created a homebrew tap. That way OS X (homebrew installed) you can start cross compiling the launchpad code simply by:

```
brew tap faroit/eabi48
brew install gcc-arm-none-eabi-48
make
```

Since it's that easy, I would propose to add this to the README and/or create an additional OS X bash script. I can compile a PR if you like

**Comment by joefocusrite** [comment]
Just tried this out and it works a treat. I'd be in favour of this over the Vagrant workflow, too. Although they're not mutually exclusive.

**Comment by jaysonturner** [comment]
<3

**Comment by dvhdr** [comment]
Nice one @faroit - send me a PR and I'll merge it!

**Comment by faroit** [comment]
added in #17
