### ISSUE TITLE
Mini support ? (and other models too)

### ISSUE THREAD

**Issue by Patrik356b** [dvhdr/launchpad-pro#13]

**Comment by dvhdr** [comment]
Sorry, this won't work with Launchpad Mini or Launchpad S. Those devices always operate with a USB host, so you're better off implementing custom behaviour there instead. Thanks for your feedback!

**Comment by matiasmorant** [comment]
Could you expand on your comment above? I have a LP mini mk3. Would like to repurpose side buttons to change Vst instruments

**Comment by mat1jaczyyy** [comment]
> Could you expand on your comment above? I have a LP mini mk3. Would like to repurpose side buttons to change Vst instruments

this is better suited for a firmware assembly hack, but this project might prove interesting: https://github.com/gabonator/Projects/tree/master/NovationLaunchpad
