### ISSUE TITLE
Add Live API support?

### ISSUE THREAD

**Issue by jonleebrown** [dvhdr/launchpad-pro#15]
Hi All, 

I wanted to add a vote for including the LiveAPI (including the JavaScript API) in the open source FW for the Launchpad Pro.

I've programmed Max for Live devices for other Launchpad models and found the API really useful--but it seems like the Pro supports a different and, in some ways, feature-reduced interface. 

I can't observe button presses or light buttons via the send_value functions (or at least I am clueless about how to fully explore and understand the LP Pro interface).

I would be willing to implement this myself if it were made available in the FW here.

Thanks,

Jonathan

**Comment by mluis** [comment]
I just opened an issue related to real-time streaming, is this Live API you're talking about related to it somehow? I'm very interested on the subject.

**Comment by dvhdr** [comment]
Check out the amazing https://github.com/mat1jaczyyy/lpp-performance-cfw by @mat1jaczyyy
