### ISSUE TITLE
Git submodule documentation

### ISSUE THREAD

**Issue by kennu** [dvhdr/launchpad-pro#19]
README should probably mention that after cloning the repository you need to run

```
git submodule init
git submodule update
```

Otherwise you'll get this error (at least on OSX when running make):

```
clang: error: no such file or directory: './tools/libintelhex/src/intelhex.cc'
```

**Comment by dvhdr** [comment]
Docs suggest you do a **git clone --recursive**, I think that accomplishes the same thing. I'll admit the docs are a bit too heavy, perhaps there should be a quickstart guide.

**Comment by kennu** [comment]
Okay thanks, I missed that because I cloned the repository before I read the docs.
