### ISSUE TITLE
hal_send_sysex() sends empty message

### ISSUE THREAD

**Issue by DatanoiseTV** [dvhdr/launchpad-pro#21]
Code:
```
int initSeq[14] = {0xF0, 0x00, 0x00, 0x7E, 0x4E, 0x00, 0x01, 0x08, 0x08, 0x02, 0x01, 0x01, 0x01, 0xF7};
hal_send_sysex(DINMIDI, initSeq, 14);
```

I see messages with the correct lenght, but containing zeros instead of the wanted values:

<img width="918" alt="bildschirmfoto 2016-09-12 um 21 46 11" src="https://cloud.githubusercontent.com/assets/6614616/18450237/79e44cc6-7932-11e6-9494-398790414af9.png">

**Comment by dvhdr** [comment]
I think that's because that code passes an array of int, not unsigned char. Not had a chance to test it myself though!

**Comment by DatanoiseTV** [comment]
Yes, that is right.
