### ISSUE TITLE
External midi input triggering launchpad midi out commands...

### ISSUE THREAD

**Issue by DubbyLabby** [dvhdr/launchpad-pro#32]
To implement an easy solution for all of us we need foot control for Launchpad app on iOS...

It will be very useful make possible (if it isn’t atm idk) to send the right midi command to the input port and Launchpad can handle it as own message to avoid the usual filtering by Launchpad app and give users the chance to program our foot controllers to launch clips/rows...

Anyone?

**Comment by dvhdr** [comment]
I guess one could program the Launchpad Pro to translate foot controller messages from its DIN port. Sorry for the ancient case resolution!
