### ISSUE TITLE
Euclidean Patterns

### ISSUE THREAD

**Issue by a1o1** [dvhdr/launchpad-pro#34]
Hello,

I would like to use the open source abilities of this firmware (awesome by the way) to implement Euclidean pattern generation feature. My questions before I go down the rabbit hole is:

- Is anyone working on this already (I'd hate to burn the time on this) and maybe I can collaborate etc.
- Do you see a blocker or issue with this type of feature (again - help me save wasting time if there are some gotchas that would prevent this today).

Ideally I'd like to have the basic inputs of pattern length, fill and offset and be able to output (in my case at least via MIDI) the Euclid Pattern aligned with the tempo. Taking this further would be to add poly rhythm features (within the grid limitations). Advanced would be something like a feature that would allow sending multiple patterns with different lengths (e.g. midi channel one looping over 16, but midi channel two looping over 13 and crazy stuff like that).

Cheers
Alan

**Comment by dvhdr** [comment]
Hi @a1o1 , what an excellent idea! I don't know of any other projects like this, and I can't think of anything that would stop you doing everything you describe. 

A great place to start would be the Subsequencely project, which shows how far it's possible to go. There are also some tools to help you.

Good luck and don't hesitate to ask if you have questions!
