### ISSUE TITLE
Access Bootloader Text toggle

### ISSUE THREAD

**Issue by mat1jaczyyy** [dvhdr/launchpad-pro#38]
In the bootloader, there is a configurable toggle for Text scrolling upon mode selection on stock firmware. Is there any way to get or set its value from the open-source firmware?

**Comment by dvhdr** [comment]
No, sorry - the bootloader is completely separate from the open firmware and can't be modified.

**Comment by mat1jaczyyy** [comment]
Not asking for modifying the bootloader, just a means to access the value of the one configuration boolean on the right side in the bootloader.

**Comment by dvhdr** [comment]
Oh, sorry, reading comprehension fail!

In principle this is doable, it's just an area of flash. In practice, we chose not to expose writes to the whole of flash memory, to avoid overwriting bits of program, other settings etc.

We could expose this as a feature, so I'll tag this issue as an improvement, but it's unlikely that we'll get to it any time soon. What's your use case?

**Comment by mat1jaczyyy** [comment]
In particular, I'm recreating the stock firmware's functionality in full, it would be a nice touch to get the scrolling text toggle back. But, it could be used for countless other things, for example enabling debug logging over SysEx.

**Comment by dvhdr** [comment]
Implemented, along with an option to read the bootloader USB device ID.
