### ISSUE TITLE
Error: "Too few arguments to function call, single argument 'adc_buffer' was not specified" 

### ISSUE THREAD

**Issue by shossa3** [dvhdr/launchpad-pro#40]
When trying to build the Simulator xcode project in the tools/osx folder, I get the "Too few arguments to function call, single argument 'adc_buffer' was not specified". Assumed that that project was intended to build without us having to change the code. Anyone know what might be the cause of the issues here? When I try to pass in a adc_buffer object, it creates some apple mach linker errors.

**Comment by dvhdr** [comment]
Ohhh, I haven't updated that since merging the adc data. Doh!

**Comment by dvhdr** [comment]
Fixed
