### ISSUE TITLE
Error trying to build app.c

### ISSUE THREAD

**Issue by shossa3** [dvhdr/launchpad-pro#41]
I get the following errors when trying to build app.c. I am including the app_defs.h and app.h header files. Not sure what's going on. Does anyone have any suggestions?

"_hal_plot_led", referenced from:

      _app_surface_event in app.o

      _app_cable_event in app.o

      _app_init in app.o

  "_hal_read_flash", referenced from:

      _app_init in app.o

  "_hal_send_midi", referenced from:

      _app_surface_event in app.o

      _app_midi_event in app.o

      _app_aftertouch_event in app.o

      _app_timer_event in app.o

  "_hal_write_flash", referenced from:

      _app_surface_event in app.o

  "_main", referenced from:

     implicit entry/start for main executable

ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dvhdr** [comment]
This ought to be fixed now (you were building the macOS project, right?)
