### ISSUE TITLE
Unable to use multiple open source firmware Launchpads at the same time

### ISSUE THREAD

**Issue by mat1jaczyyy** [dvhdr/launchpad-pro#43]
On stock firmware, we can select an ID for our Launchpads in the bootloader, so the Launchpad can present itself as a different MIDI port to avoid conflicts (USB PID 0051 to 0060).

This ID selection is entirely ignored in the open source firmware, and the Launchpad will always present itself as USB PID 4051, no matter what ID is really selected in the bootloader. This makes it impossible to properly utilize multiple open source firmware Launchpads at the same time.

This would be a very welcome fix for anyone who owns multiple Launchpads, and I feel this is a very basic thing that shouldn't really have been an issue from the start.

**Comment by dvhdr** [comment]
You're right. I left it out because I didn't see USB being much of a use case. But then, I didn't expect someone to come along and re-implement the stock features (I mean, wow, great work!) on the open SDK.

**Comment by mat1jaczyyy** [comment]
Live integration was a special challenge ;) Thanks for acknowledging the issue, I've got a bunch of users affected so I'm hoping it gets patched.

On an unrelated note, any chance we could get in touch? I've got multiple issues to report on the USB Driver for the Launchpad that I've been trying to report to you guys for a while now, I believe one of them has been assigned a ticket number but I've gotten no updates for months now. Some of them are a real dealbreaker for the software I'm developing.

**Comment by mat1jaczyyy** [comment]
@dvhdr ?

**Comment by dvhdr** [comment]
Mailed you :)

**Comment by dvhdr** [comment]
Just pushed a change to the lib which supports the bootloader device ID. Note that this will only partly help on Windows - the Novation driver will not yet match the open firmware device (but that's a separate issue, as it's only required for multi-client operation).

**Comment by mat1jaczyyy** [comment]
Thanks for the firmware side fix @dvhdr ! Waiting for the driver fixes then. Could you get back to me over email about the other issues I reported? I've been awaiting your response for 2 weeks already.
